import type { NextPage } from "next";
import Head from "next/head";
import Example from "../components/Example";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Nextjs - gql</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Example nextjs with gql</h1>
        <Example />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
